#ifndef __APP_MAIN_H__
#define __APP_MAIN_H__

#define RESET_WIFI_AND_BLE_MESH_PIN GPIO_NUM_21
#define MODE_CLIENT_OR_SERVER_PIN GPIO_NUM_14
#define WIFI_STATUS GPIO_NUM_17
#define BLE_MESH_INITIALIZED_PIN GPIO_NUM_16
#define BUTTON_1 GPIO_NUM_20
#define BUTTON_2 GPIO_NUM_19
#define RELAY_1 GPIO_NUM_12
#define RELAY_2 GPIO_NUM_4
#define V_RELAY_1 GPIO_NUM_25
#define V_RELAY_2 GPIO_NUM_26

#endif