name: aithings
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  firebase_remote_config: ^5.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  intl: 0.18.1
  package_info_plus: ^8.0.0
  upgrader: ^10.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
